print ("Please enter 5 numbers.")
number1=int(input())
number2=int(input())
number3=int(input())
number4=int(input())
number5=int(input())
print ("the average of those numbers is:")
print ((number1+number2+number3+number4+number5)/5)