print ("Please enter five numbers.")
number1=float(input())
number2=float(input())
number3=float(input())
number4=float(input())
number5=float(input())
print ("the average of those numbers is:")
print ((number1+number2+number3+number4+number5)/5)